services:
  feishu-shortcut:
    build: .
    container_name: vidu-feishu-shortcut-dev
    ports:
      - "3000:3000"
    volumes:
      # 挂载源代码目录，支持热重载
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=dev
      - PORT=3000
    # 开发模式下使用nodemon进行热重载
    command: npm run dev
    restart: unless-stopped
    networks:
      - feishu-network

networks:
  feishu-network:
    driver: bridge 